import type { BlogPost } from "@/lib/blogTypes";

const published = "2026-09-24";

export const guidePosts: BlogPost[] = [
  {
    slug: "when-business-outgrows-spreadsheets",
    title: "How to Know When Your Business Has Outgrown Spreadsheets",
    description: "Practical signs that spreadsheets are becoming an operational risk, plus when to improve them, buy software, or build a custom system.",
    date: published,
    category: "Business software guide",
    cluster: "Business Software",
    keywords: ["outgrown spreadsheets", "replace spreadsheets", "custom business software"],
    intro: "Spreadsheets are excellent tools. They are quick to start, familiar, flexible, and often the right answer for a small process. The question is not whether spreadsheets are good or bad; it is whether the work has developed relationships, controls, and collaboration needs that a grid can no longer represent reliably.",
    sections: [
      {
        id: "useful-start",
        title: "Spreadsheets are often the right starting point",
        body: [
          "A spreadsheet can validate a workflow before anyone commits to software. One person can track a modest list of customers, jobs, costs, or stock with little setup, and formulas can answer straightforward reporting questions. Replacing that too early may introduce cost without removing meaningful friction.",
          "The first warning is therefore not the size of the file. It is the amount of human coordination required to keep it correct. A large, stable reference sheet may be safer than a small workbook that five people edit while copying data between email, messaging, accounting, and scheduling tools.",
        ],
      },
      {
        id: "warning-signs",
        title: "Signs the workflow has become operationally fragile",
        body: [
          "Version names such as final-v7 and unexplained duplicate rows are visible symptoms. More important symptoms are hidden: a formula can be overwritten, permissions apply to a whole file rather than a role, and nobody can confidently explain which record is authoritative.",
          "Pay attention when staff repeatedly reconcile conflicting copies, retype the same customer or job details, wait for another person to close a file, or rely on one employee who understands the formulas. Those are process costs even when the software itself appears free.",
        ],
        bullets: [
          "Several people need to update the same records at the same time.",
          "Customer, job, document, payment, and status data must stay connected.",
          "Different roles should see or change different information.",
          "Mobile staff need reliable access and data entry away from a desk.",
          "Reports require repeated cleanup before they can be trusted.",
          "Other systems need consistent integrations rather than copy and paste.",
        ],
      },
      {
        id: "relationships",
        title: "Relationships are usually the turning point",
        body: [
          "A spreadsheet stores rows well, but an operating system must preserve relationships. One customer may have many jobs; each job may have appointments, quotes, invoices, files, payments, and an audit history. Keeping those links intact with tabs, lookups, and naming rules becomes progressively more fragile.",
          "TradesMate illustrates the shape of this problem without proving that every trade business needs custom software. Its customers, jobs, schedules, quotes, invoices, expenses, and payments are connected because each later step depends on reliable information from the earlier one.",
        ],
        diagram: ["Customer", "Job", "Quote", "Invoice", "Payment"],
      },
      {
        id: "options",
        title: "Four reasonable paths forward",
        body: [
          "Keeping the spreadsheet is sensible when the process is stable, ownership is clear, and errors are inexpensive. Improving it with validation, protected ranges, forms, or carefully governed automation can extend its useful life. Off-the-shelf software is often best when the workflow is common and the team can adapt to the product.",
          "Custom software becomes a serious option when the workflow is distinctive, integrations matter, or forcing the business into a generic product creates ongoing workarounds. The decision should compare total process cost, adoption, and risk, not only licence fees or development cost.",
        ],
        table: {
          caption: "Choosing the next step",
          headers: ["Option", "Best fit", "Main trade-off"],
          rows: [
            ["Keep spreadsheets", "Stable, low-risk work owned by a small group", "Manual control remains important"],
            ["Improve existing tools", "The process works but needs validation or automation", "Complex automation can become its own system"],
            ["Buy software", "The workflow is common and configurable", "The business may need to adapt"],
            ["Build software", "The workflow or integration is strategically specific", "Requires discovery, delivery, and ownership"],
          ],
        },
      },
      {
        id: "decision",
        title: "Make the decision from the workflow, not the file",
        body: [
          "Map where information enters, who changes it, which decisions depend on it, and what happens when it is wrong. Estimate the time spent searching, reconciling, re-entering, and correcting. Include delayed invoices, missed follow-ups, and reporting uncertainty where they genuinely occur.",
          "A useful replacement brief describes those bottlenecks and the minimum connected workflow that would remove them. It does not need to prescribe a database or framework. That leaves room to discover whether a simpler tool change, an integration, or a focused custom application is the proportionate answer.",
        ],
      },
    ],
    primaryLink: { href: "/solutions/replace-spreadsheets-with-custom-software", label: "Explore the spreadsheet replacement path", description: "See how discovery turns a fragile workbook workflow into a scoped software decision." },
    relatedLinks: [
      { href: "/services/custom-business-software", label: "Custom business software development" },
      { href: "/work/tradesmate", label: "TradesMate product evidence" },
    ],
  },
  {
    slug: "mobile-app-vs-web-app-for-business",
    title: "Mobile App vs Web App for a Business: How to Decide",
    description: "Compare mobile and web applications by users, devices, offline needs, notifications, distribution, administration, and long-term ownership.",
    date: published,
    category: "Product decision guide",
    cluster: "Mobile Development",
    keywords: ["mobile app vs web app", "business app decision", "web or mobile application"],
    intro: "The best interface follows the work. A mobile app is not automatically more modern, and a web app is not automatically simpler or cheaper. Start with who uses the product, where they use it, and which device capabilities or desktop workflows are essential.",
    sections: [
      { id: "users", title: "Begin with users and context", body: ["A field worker checking jobs throughout the day has a different context from an administrator comparing records across a wide screen. Frequency matters too: repeated daily use can justify installation and a purpose-built mobile flow, while occasional customers may prefer opening a link without installing anything.", "List the main user groups separately. For each one, record the typical device, environment, session length, connectivity, and tasks. One product can legitimately need both mobile and web clients rather than forcing every user through the same interface."], bullets: ["Who performs the task?", "Where and how often is it performed?", "Is the work quick and focused or dense and comparative?", "Does it rely on camera, location, notifications, or local files?"] },
      { id: "comparison", title: "Compare capabilities, not labels", body: ["Native and cross-platform mobile apps generally provide strong notification, camera, storage, sharing, and offline options. Web applications excel at immediate browser access, desktop administration, complex tables, and centrally deployed updates. Modern web capabilities narrow some gaps, but support still varies by browser and operating system.", "Distribution has operational consequences. Mobile releases pass through store review and users may delay updates. Web releases can reach users immediately, but browser compatibility and session security still require care."], table: { caption: "Typical strengths and constraints", headers: ["Consideration", "Mobile app", "Web app"], rows: [["Installation", "Usually required", "Browser access"], ["Push notifications", "Strong platform support", "Varies by browser and platform"], ["Device integration", "Strong and predictable", "Available but more variable"], ["Desktop workflows", "Less natural", "Strong"], ["Offline", "Can be designed deeply", "Possible, architecture dependent"], ["Updates", "Store and user update cycle", "Centrally deployed"]] } },
      { id: "combined", title: "A combined product is often the honest answer", body: ["Many business systems use a focused mobile app for work in motion and a web application for setup, reporting, administration, or customer support. Both can share accounts, permissions, business rules, and data through the same backend API.", "This is not automatically twice the project. Shared backend work can serve both clients, but each interface still needs product design, testing, release management, and support. Scope each client around the tasks it genuinely improves."], diagram: ["Shared backend and business rules", "Mobile workflows + Web administration"] },
      { id: "decision", title: "A practical decision sequence", body: ["Choose web-first when broad access, desktop work, and frictionless distribution dominate. Choose mobile-first when the product is used frequently on phones and depends on device or offline capabilities. Choose both when distinct user groups have distinct contexts and the shared business case supports both.", "Before committing, prototype the critical workflow at realistic screen sizes and test it with representative users. The right question is not which technology is fashionable; it is which delivery model removes the most friction without creating unnecessary ownership cost."], bullets: ["Define the primary workflow and primary user.", "Identify non-negotiable device and offline requirements.", "Separate operational mobile tasks from administrative desktop tasks.", "Scope release, analytics, support, and update responsibilities."] },
    ],
    primaryLink: { href: "/solutions/build-an-app-for-my-business", label: "Plan an app for your business", description: "Turn the device and workflow decision into a proportionate product scope." },
    relatedLinks: [{ href: "/services/mobile-app-development", label: "Mobile app development" }, { href: "/services/web-app-development", label: "Web application development" }],
  },
  {
    slug: "what-should-an-mvp-include",
    title: "What Should Be Included in an MVP?",
    description: "A practical MVP scoping guide covering the core workflow, backend, accounts, admin, integrations, testing, security, and what to defer.",
    date: published,
    category: "Product planning guide",
    cluster: "MVP & Product",
    keywords: ["what should an MVP include", "MVP feature scope", "minimum viable product planning"],
    intro: "An MVP is the smallest credible product that can test an important assumption with real users. It is not every feature compressed into a deadline, and it is not a broken prototype presented as production software.",
    sections: [
      { id: "hypothesis", title: "Define the decision the MVP must enable", body: ["Start with one primary user, one painful problem, and one observable outcome. A marketplace may need to learn whether supply and demand can complete one transaction. An internal tool may need to prove that a connected workflow removes duplicate entry. Without a decision, 'minimum' becomes arbitrary.", "Write the product hypothesis in plain language and define the evidence that would change your next investment decision. Downloads alone are rarely enough; completed workflows, repeat use, time saved, or successful handoffs are usually more informative."], bullets: ["Primary user and problem", "Core action or workflow", "Success and failure signals", "Time window for learning"] },
      { id: "core", title: "Include the complete core workflow", body: ["A viable product lets the user complete the central job from beginning to end. A booking MVP needs more than a booking form if nobody can manage availability or confirm the result. A quoting tool needs the data, calculation, document, and status steps required to make the quote usable.", "Supporting screens should exist only where the core flow depends on them. This usually includes purposeful onboarding, clear empty and error states, and enough account recovery or support handling to avoid stranding users."], diagram: ["User enters the workflow", "Core action is completed", "Outcome is recorded and measurable"] },
      { id: "platform", title: "Do not forget the invisible product", body: ["The interface is only part of the MVP. Authentication, authorization, data storage, essential business rules, basic administration, logging, backups, and deployment are part of a credible service when the product handles accounts or operational data.", "Security and testing should be proportional to risk, not postponed as decoration. An MVP that loses data, exposes another user's records, or cannot recover from common failures tests the wrong thing: whether users tolerate an unreliable implementation."], bullets: ["Essential backend and data model", "Roles and permissions", "Minimal administration and support tools", "Analytics tied to the hypothesis", "Error handling, monitoring, and backups", "Release and store requirements where applicable"] },
      { id: "later", title: "What commonly belongs after the first release", body: ["Advanced reporting, deep customization, secondary user roles, broad integration catalogues, elaborate automation, and edge-case workflows often belong later. They may be valuable, but they dilute the first learning cycle if the core proposition is still unproven.", "Defer intentionally. Record the reason, dependency, and signal that would bring an item forward. A managed later list prevents the MVP from feeling like an arbitrary rejection of stakeholder ideas."], table: { caption: "A useful scope test", headers: ["Question", "Include now when...", "Defer when..."], rows: [["Does the core flow fail without it?", "Yes", "It only improves convenience"], ["Does it test the main assumption?", "Directly", "It measures a secondary idea"], ["Is it required for safe operation?", "Security or data integrity depends on it", "It is cosmetic polish"], ["Can the team operate manually at first?", "No practical fallback exists", "A low-volume manual step is acceptable"]] } },
      { id: "scope", title: "Turn the MVP into a release plan", body: ["Describe user journeys and acceptance outcomes rather than collecting disconnected feature nouns. Identify integrations and unknowns early, because payment, identity, legacy data, and external APIs can dominate risk even when their screens look small.", "Plan a short discovery step, a build sequence that produces testable increments, and a measured release. The result should be deliberately narrow but coherent enough that the feedback is about the product idea rather than missing basics."],
      },
    ],
    primaryLink: { href: "/solutions/build-an-mvp", label: "Shape your MVP scope", description: "See the commercial scoping path for turning an idea into a credible first release." },
    relatedLinks: [{ href: "/services/mvp-development", label: "MVP development services" }, { href: "/blog/prepare-for-software-development-estimate", label: "Prepare for a development estimate" }],
  },
  {
    slug: "mobile-app-for-existing-web-platform",
    title: "How to Plan a Mobile App for an Existing Web Platform",
    description: "Assess an existing web platform, backend, authentication, API coverage, mobile workflows, offline needs, notifications, and release planning.",
    date: published,
    category: "Platform extension guide",
    cluster: "Mobile Development",
    keywords: ["mobile app for existing web platform", "add mobile app to website", "existing platform mobile app"],
    intro: "Adding mobile is usually a platform-extension project, not a smaller copy of the website. The most important early work is understanding what can be reused safely and what the phone-specific experience should change.",
    sections: [
      { id: "audit", title: "Audit the platform before designing screens", body: ["Document the current frontend, backend, database, hosting, identity provider, file storage, integrations, and operational tools. Confirm which component owns each business rule. A polished website can still hide a server designed only to render pages rather than serve external clients.", "Review production constraints as well as code: rate limits, observability, deployment process, data protection, and who can change the backend. These determine whether mobile work can proceed independently or needs platform changes first."],
      },
      { id: "three-situations", title: "Recognize which of three situations you have", body: ["When a documented, versioned API already covers the mobile workflows, the app can focus on product design, client implementation, and release. When a backend exists but endpoint coverage is incomplete, mobile and API work should be planned together. When the application was never designed for external clients, an API layer and security model may be a substantial part of the project.", "None of these situations is inherently bad. The risk comes from assuming the first while actually having the third."], table: { caption: "Existing platform readiness", headers: ["Situation", "Likely work", "Main risk"], rows: [["API is ready", "Mobile client and release", "Hidden mobile-specific gaps"], ["Backend needs extension", "Client plus planned API changes", "Coordination and versioning"], ["No external-client architecture", "API, identity, rules, then client", "Underestimating platform work"]] } },
      { id: "mobile-workflow", title: "Design for the phone's job", body: ["Select the workflows that benefit from immediacy, mobility, camera or upload access, notifications, or offline continuity. Dense administration may remain better on the web. Shared accounts do not require identical navigation or feature parity.", "Specify push notification events, deep-link destinations, upload behaviour, background and offline expectations, and what happens on slow or interrupted networks. These are product decisions with backend consequences."], bullets: ["Shared sign-in and permission model", "Mobile-specific navigation and task depth", "Push, uploads, deep links, and sharing", "Offline queue and conflict behaviour", "Analytics and support diagnostics"] },
      { id: "architecture", title: "Extend through a stable boundary", body: ["A mobile app normally communicates with an appropriate API rather than accessing the production database. The API enforces authorization, validation, and business rules consistently for web and mobile clients.", "PubPlay and Come Together demonstrate multi-interface product shapes where web, mobile, and backend responsibilities must stay coordinated. They are evidence of architecture and delivery work, not claims that every platform needs the same design."], diagram: ["Existing platform", "Backend / API", "Web client + Mobile client"] },
      { id: "release", title: "Plan release as part of the product", body: ["Store accounts, privacy disclosures, screenshots, review requirements, staged rollout, crash reporting, and support ownership should enter the plan before the final week. Coordinate API compatibility so an older installed app continues to work while a new release is under review.", "A focused first mobile release should prove the highest-value phone workflow, then add coverage from observed use. Rebuilding the entire web product on a smaller screen usually delays that learning."],
      },
    ],
    primaryLink: { href: "/solutions/mobile-app-for-existing-web-platform", label: "Plan your platform extension", description: "Assess reuse, API work, and a focused mobile release." },
    relatedLinks: [{ href: "/services/mobile-app-development", label: "Mobile app development" }, { href: "/work/pubplay", label: "PubPlay platform evidence" }, { href: "/work/come-together", label: "Come Together platform evidence" }],
  },
  {
    slug: "can-mobile-app-use-existing-backend-api",
    title: "Can a Mobile App Use an Existing Backend or API?",
    description: "A technical planning guide to API coverage, authentication, authorization, uploads, realtime events, versioning, staging, and network reliability.",
    date: published,
    category: "Backend integration guide",
    cluster: "Mobile Development",
    keywords: ["mobile app existing backend", "connect mobile app to API", "mobile backend integration"],
    intro: "Yes, a mobile app can often reuse an existing backend, and that is usually preferable to duplicating business logic. Reuse depends on whether the backend exposes a secure, stable contract that covers the app's workflows under real mobile network conditions.",
    sections: [
      { id: "api-boundary", title: "Use an API boundary, not direct database access", body: ["The mobile client should normally call an HTTPS API such as REST or GraphQL. The backend validates input, applies permissions and business rules, reads or writes data, and returns an intentional response. Direct production database access would expose credentials and couple releases to internal storage details.", "An API also gives multiple clients a shared place for rules. The web interface, mobile app, and administrative tools can present different experiences without inventing different meanings for the same status or permission."], diagram: ["Mobile application", "Authenticated API", "Business rules and data"] },
      { id: "identity", title: "Verify authentication and authorization separately", body: ["Authentication establishes who the user is. Authorization determines which records and actions that identity may access. A token that successfully signs in is not evidence that object-level permissions are correct.", "Review token lifetime, refresh, revocation, secure device storage, password reset, multi-factor requirements, and role enforcement. Mobile logout, lost-device handling, and account deletion also need defined server behaviour."],
      },
      { id: "coverage", title: "Check endpoint coverage against complete workflows", body: ["A list endpoint is not enough if the app must filter, paginate, update, upload files, or complete a state transition. Map each mobile journey to requests and responses, then identify missing validation, server rules, and administrative support.", "Documentation should describe payloads, errors, permissions, and examples. An OpenAPI specification or maintained equivalent reduces ambiguity, but it must reflect actual production behaviour."], bullets: ["Create, read, update, and domain-specific actions", "Pagination, search, and filtering", "Uploads and download authorization", "Consistent error codes and user-safe messages", "Notification registration and event triggers", "Realtime subscriptions where genuinely required"] },
      { id: "reliability", title: "Design for unreliable networks", body: ["Mobile requests are interrupted by tunnels, handovers, backgrounding, and constrained data. Timeouts, retries, idempotency, caching, and queued writes must be designed so a retry does not create duplicate payments, bookings, or documents.", "Offline support ranges from read-only caching to full synchronized editing. Define exactly which operations work offline, how conflicts are resolved, and what the user sees while data is pending."],
      },
      { id: "operations", title: "Version, test, and observe the integration", body: ["Installed apps cannot all update at once. Backward-compatible API changes, explicit deprecation windows, and version-aware monitoring protect older clients. Use a staging environment with representative data and integrations rather than testing against production.", "Logs should correlate a mobile request with backend processing without recording secrets. Crash reports, API latency, failed requests, and notification delivery help separate client defects from network and server problems."], table: { caption: "Backend readiness questions", headers: ["Area", "Evidence to look for"], rows: [["Contract", "Current API documentation and representative examples"], ["Security", "Token handling and object-level authorization"], ["Coverage", "Every core mobile workflow has supported operations"], ["Reliability", "Timeout, retry, idempotency, and offline decisions"], ["Operations", "Staging, logs, metrics, and version policy"]] } },
    ],
    primaryLink: { href: "/solutions/connect-mobile-app-to-existing-backend", label: "Assess your existing backend", description: "Identify reusable API capability and the extensions a mobile client needs." },
    relatedLinks: [{ href: "/services/backend-api-development", label: "Backend and API development" }, { href: "/services/mobile-app-development", label: "Mobile app development" }, { href: "/services/react-native-development", label: "React Native development" }],
  },
  {
    slug: "what-determines-custom-software-cost",
    title: "What Determines the Cost of Custom Software?",
    description: "Understand the scope and risk drivers behind custom software cost without relying on fabricated price ranges or feature-count shortcuts.",
    date: published,
    category: "Software investment guide",
    cluster: "Cost & Modernization",
    keywords: ["custom software cost factors", "how much does an app cost", "software estimate scope"],
    intro: "A reliable software estimate describes a defined system, delivery approach, and uncertainty. 'How much does an app cost?' has no accurate universal answer because two products with a similar number of screens can have entirely different rules, integrations, data, and operational risk.",
    sections: [
      { id: "scope", title: "Interfaces and workflows shape the visible scope", body: ["A mobile app, customer web portal, internal administration interface, and reporting console are separate user experiences even when they share a backend. Each adds product design, accessibility, testing, and release work.", "Workflow depth matters more than a raw feature count. A quote button may imply customer records, line items, tax rules, numbering, PDF generation, email delivery, status history, and permissions. Estimates improve when requirements describe outcomes and exceptions rather than short labels."],
      },
      { id: "platform", title: "Backend, data, and integrations shape the hidden scope", body: ["Accounts, roles, business rules, APIs, storage, search, background jobs, audit history, and administration make the product operate. Payments, identity providers, accounting services, maps, messaging, and legacy systems add external contracts and failure modes.", "Existing data may need cleaning, mapping, validation, and staged migration. A migration that preserves history and allows rollback is different from importing a clean contact list once."], bullets: ["Number of clients: web, mobile, admin, partner", "Roles, permissions, and approval paths", "Documents, media, search, and reporting", "Payments and external integrations", "Offline sync or realtime behaviour", "Legacy migration and coexistence"] },
      { id: "quality", title: "Quality expectations are part of scope", body: ["Testing effort depends on consequences. A marketing calculator and a financial document workflow should not receive identical validation. Supported devices, browsers, accessibility, security review, performance, backups, monitoring, and incident response all affect delivery.", "Deployment is also product work. Mobile store review, production infrastructure, domain and email configuration, analytics, privacy material, and handover should be visible in the estimate rather than treated as free final steps."],
      },
      { id: "uncertainty", title: "Uncertainty changes the estimate", body: ["Unknown legacy code, undocumented APIs, unresolved business rules, and untested third-party constraints create ranges because they can change the implementation path. A short discovery or technical spike can be cheaper than hiding those unknowns inside a falsely precise fixed figure.", "An estimate should state assumptions, exclusions, dependencies, and how change will be handled. Compare estimates on scope and confidence, not only the final number."], table: { caption: "Common cost drivers", headers: ["Driver", "Why it matters", "Useful evidence"], rows: [["Workflow depth", "More states, exceptions, and rules", "User journeys and examples"], ["Interfaces", "Each client needs design and testing", "User/device matrix"], ["Integrations", "External contracts and failure handling", "API documentation and access"], ["Data", "Migration, quality, privacy, reporting", "Samples and volumes"], ["Operations", "Deployment, monitoring, support", "Target environments and service expectations"]] } },
      { id: "prepare", title: "Improve the estimate before discussing price", body: ["Bring the business problem, primary users, core workflow, must-have outcome, existing systems, integrations, data constraints, and launch priority. Reference products are useful when you explain what is relevant rather than asking for a clone.", "You do not need a complete technical architecture or every screen designed. A good discovery conversation should turn operational context into options, identify unknowns, and separate the first valuable release from later expansion."],
      },
    ],
    primaryLink: { href: "/solutions/custom-software-cost", label: "Understand the estimating process", description: "See how scope, uncertainty, and delivery choices become a commercial estimate." },
    relatedLinks: [{ href: "/services/custom-business-software", label: "Custom business software" }, { href: "/blog/prepare-for-software-development-estimate", label: "What to prepare for an estimate" }],
  },
  {
    slug: "rewrite-vs-modernize-existing-software",
    title: "Rewrite or Modernize Existing Software?",
    description: "Compare incremental modernization with a full rewrite across risk, APIs, frontends, dependencies, data migration, staged rollout, and business continuity.",
    date: published,
    category: "Modernization guide",
    cluster: "Cost & Modernization",
    keywords: ["rewrite vs modernize software", "legacy software modernization", "replace existing application"],
    intro: "A rewrite is emotionally attractive because it promises a clean start. It also discards years of encoded business behaviour and creates a period in which two systems must be understood at once. Modernization should begin by identifying which constraints actually block the business.",
    sections: [
      { id: "risk", title: "Why full rewrites are risky", body: ["Existing software contains documented features, undocumented edge cases, data conventions, integrations, and staff habits. Rebuilding visible screens does not automatically reproduce those behaviours. Long rewrite programmes can also leave the current product under-maintained while the replacement is not yet useful.", "This does not mean rewrites are never justified. It means 'old code' alone is not a business case. The decision should consider change frequency, defect risk, security support, performance, talent availability, and the cost of safely releasing improvements."],
      },
      { id: "incremental", title: "Modernization can replace one constraint at a time", body: ["A team may replace a client interface while retaining a stable backend, introduce an API in front of legacy logic, upgrade dependencies in stages, extract a high-change workflow, or move reporting away from the transaction system. These approaches preserve working behaviour while creating clearer boundaries.", "Prioritize changes that unlock future delivery: automated tests around critical rules, observability, repeatable deployment, supported runtimes, and an API contract can be more valuable than a cosmetic rewrite."], diagram: ["Protect critical behaviour", "Create a stable boundary", "Replace constrained components", "Retire legacy safely"] },
      { id: "data", title: "Treat data migration as a product stream", body: ["Data has meaning beyond column names. Status values, duplicates, missing references, historical documents, permissions, and retention obligations must be mapped and validated. Decide whether systems will coexist, synchronize temporarily, or switch at a controlled cutover.", "Use rehearsed migrations, reconciliation reports, rollback plans, and explicit ownership. The new application is not complete if users cannot trust its history."],
      },
      { id: "rebuild", title: "When a rebuild may be justified", body: ["A rebuild can be appropriate when the platform is unsupported, security cannot be remediated proportionately, architecture prevents essential change, or the product direction is fundamentally different. It is stronger when the business can define a narrow replacement sequence rather than waiting for a big-bang replica.", "Even then, reuse knowledge and verified rules. Instrument the current workflow, interview operators, capture representative data, and decide which legacy behaviours should deliberately disappear."], table: { caption: "Decision signals", headers: ["Signal", "Modernize incrementally", "Consider rebuild"], rows: [["Core rules", "Valuable and testable", "Poorly understood or fundamentally changing"], ["Architecture", "Boundaries can be introduced", "Essential change remains blocked"], ["Data", "Can coexist or migrate in stages", "New model is fundamentally different"], ["Release", "Small changes can reach production", "Current release path is unsalvageable"]] } },
      { id: "plan", title: "Build a staged transition plan", body: ["Define the measurable constraint, map dependencies, protect critical behaviour with tests, and choose a first boundary. Plan coexistence, support, migration, and rollback before replacing a production component.", "A modernization roadmap should show business value at intermediate stages. If benefits appear only after every component is replaced, the plan carries many of the same risks as a big-bang rewrite."],
      },
    ],
    primaryLink: { href: "/solutions/modernize-existing-software", label: "Plan a modernization path", description: "Assess constraints and choose a staged, evidence-led transition." },
    relatedLinks: [{ href: "/services/backend-api-development", label: "Backend and API development" }, { href: "/services/web-app-development", label: "Web application development" }],
  },
  {
    slug: "react-native-vs-native-business-app",
    title: "React Native vs Native Apps for Business Software",
    description: "A business-focused comparison of React Native and native mobile development across code sharing, platform features, performance, teams, and ownership.",
    date: published,
    category: "Mobile technology guide",
    cluster: "Mobile Development",
    keywords: ["React Native vs native business app", "cross platform business software", "native mobile app decision"],
    intro: "React Native and native development are delivery choices, not product strategies. Either can produce excellent business software. The right decision follows platform requirements, team capability, performance constraints, release plans, and long-term ownership.",
    sections: [
      { id: "shared", title: "What a shared codebase actually means", body: ["React Native can share substantial application logic and interface code across iOS and Android while still producing platform applications. Sharing is not absolute: permissions, notifications, purchases, background work, widgets, and specialist device integrations may need platform-specific configuration or native modules.", "The benefit is strongest when the product experience is largely consistent across platforms and the team can maintain shared TypeScript and deliberate native edges. A poorly structured shared codebase can spread platform compromises rather than reduce work."],
      },
      { id: "native", title: "Where native development is compelling", body: ["Native Swift and Kotlin provide direct access to platform APIs, tooling, and interface conventions. This can be valuable for deep operating-system integration, demanding media or graphics, highly platform-specific experiences, or teams already organized around separate native products.", "Native does not remove complexity; it distributes implementation across codebases. Product rules, analytics, backend contracts, and release coordination still need consistency."],
      },
      { id: "comparison", title: "Compare the constraints that matter to ownership", body: ["Consider the expected lifetime, release frequency, hiring environment, existing web or TypeScript capability, native expertise, and who will maintain the app. Performance discussions should name a workload: ordinary forms and lists differ from live video processing or intensive graphics.", "Prototype the riskiest platform capability before making an architecture promise. A small native module inside React Native may be proportionate; in other cases, repeated platform-specific work can erase the value of sharing."], table: { caption: "Decision considerations", headers: ["Consideration", "React Native", "Native"], rows: [["Code sharing", "High for suitable product flows", "Separate platform implementations"], ["Platform APIs", "Supported directly or through modules", "Direct access"], ["Team shape", "Cross-platform product team", "Platform-specialist teams"], ["UI differences", "Can share while adapting", "Naturally platform-specific"], ["Maintenance", "One shared core plus native edges", "Two application codebases"]] } },
      { id: "requirements", title: "Let requirements make the decision", body: ["React Native is a strong candidate for account-based business apps, field workflows, commerce, content, and connected SaaS clients when required device capabilities are supported. Native is a strong candidate where the operating system itself is central to the product or where specialized performance and platform behaviour dominate.", "Neither option is automatically faster, cheaper, or higher quality. Delivery quality depends on scope, architecture, testing, and the team's ability to own the chosen stack."], bullets: ["List platform-specific features and background behaviour.", "Name performance-sensitive workloads.", "Decide whether iOS and Android must launch together.", "Review the skills and ownership model after launch.", "Test the highest-risk integration early."] },
    ],
    primaryLink: { href: "/services/react-native-development", label: "Explore React Native development", description: "Review the cross-platform delivery approach for a real business application." },
    relatedLinks: [{ href: "/services/mobile-app-development", label: "Mobile app development" }, { href: "/blog/mobile-app-vs-web-app-for-business", label: "Mobile app vs web app" }],
  },
  {
    slug: "how-web-mobile-backend-work-together",
    title: "How Web, Mobile, and Backend Systems Work Together",
    description: "A plain-language architecture guide to databases, backend APIs, shared business rules, authentication, web clients, mobile clients, and admin tools.",
    date: published,
    category: "Software architecture guide",
    cluster: "SaaS & Architecture",
    keywords: ["web mobile backend architecture", "how apps and backend work", "SaaS platform architecture"],
    intro: "A connected product is usually several cooperating systems. The browser page or phone screen is the visible client; a backend applies rules and coordinates data; storage preserves records. Understanding those responsibilities helps non-specialists scope changes and ask better questions.",
    sections: [
      { id: "layers", title: "A useful conceptual model", body: ["The database stores structured records and relationships. The backend or API authenticates requests, enforces permissions and business rules, coordinates integrations, and exposes intentional operations. Web, mobile, and administrative clients present workflows for different users.", "Not every product follows this exact architecture. Some features run locally, some platforms use managed services, and some systems split the backend into several components. The model is useful because it separates what users see from where authoritative decisions happen."], diagram: ["Database and file storage", "Backend / API and business rules", "Web app / Mobile app / Admin interface"] },
      { id: "rules", title: "Shared rules keep multiple clients consistent", body: ["If both web and mobile can approve a booking or issue an invoice, the server should normally enforce the authoritative transition. Client validation improves usability but cannot be the only control because clients can be outdated, interrupted, or manipulated.", "A stable API allows each interface to suit its context while sharing account, permission, and data meaning. This is why adding mobile is often an extension of the platform rather than a duplicate standalone project."],
      },
      { id: "identity", title: "Authentication starts a request; authorization governs it", body: ["Users may sign in through passwords, magic links, social identity, or enterprise providers. The backend validates identity and then checks whether that user may access the requested organization, venue, event, customer, or document.", "Administrative tools often need broader privileges and stronger audit history. Designing roles centrally avoids relying on hidden buttons as a security boundary."],
      },
      { id: "examples", title: "Different interfaces can serve one platform", body: ["PubPlay connects venue management, player participation, and display experiences around shared events and scores. Come Together combines web and mobile surfaces around member and event activity. These products support the architectural principle without implying that their exact components suit every business.", "The useful design question is which user needs which client. A public web journey, a staff mobile workflow, and an internal admin console can share a platform while remaining intentionally different products."],
      },
      { id: "backend-matters", title: "Backend design affects product change", body: ["Clear domain rules, versioned contracts, logs, and automated tests make it easier to add clients and integrations. Tight coupling, undocumented endpoints, and rules duplicated across interfaces make apparently small changes risky.", "Before adding a client, map ownership of data and rules, review API coverage, identify realtime or offline needs, and define how old and new versions coexist. That creates a delivery plan grounded in the current system."], table: { caption: "Typical responsibilities", headers: ["Layer", "Primary responsibility", "Examples"], rows: [["Client", "Interaction and local presentation", "Web, mobile, admin"], ["Backend/API", "Rules, permissions, orchestration", "Accounts, workflow states, integrations"], ["Storage", "Durable records and files", "Database, object storage"], ["Operations", "Reliable running and diagnosis", "Deployment, logs, monitoring, backups"]] } },
    ],
    primaryLink: { href: "/services/saas-development", label: "Explore SaaS platform development", description: "Plan connected client, backend, data, and operational responsibilities." },
    relatedLinks: [{ href: "/services/backend-api-development", label: "Backend and API development" }, { href: "/solutions/mobile-app-for-existing-web-platform", label: "Add mobile to an existing platform" }, { href: "/work/pubplay", label: "PubPlay product evidence" }],
  },
  {
    slug: "prepare-for-software-development-estimate",
    title: "What to Prepare Before Asking for a Software Development Estimate",
    description: "Prepare the business problem, users, workflow, must-haves, platforms, systems, integrations, data, priorities, and constraints needed for a useful estimate.",
    date: published,
    category: "Project planning guide",
    cluster: "MVP & Product",
    keywords: ["prepare software development estimate", "app project brief", "software quote requirements"],
    intro: "You do not need a complete specification to start an estimate conversation. You do need enough context to distinguish the first valuable product from assumptions, later ideas, and technical unknowns.",
    sections: [
      { id: "problem", title: "Describe the problem before the feature list", body: ["Explain what happens today, who is affected, where time or risk accumulates, and what a better outcome would look like. A feature such as 'dashboard' can mean almost anything; a need to see overdue invoices by business unit gives the discussion a testable purpose.", "Include scale where known: user groups, locations, transaction volume, data sensitivity, and timing. Approximate ranges are useful when clearly marked as estimates."],
      },
      { id: "workflow", title: "Walk through the primary user and workflow", body: ["Name the primary user, the trigger that starts their task, the decisions they make, the information they need, and the result. Then identify other roles such as administrators, customers, managers, or support staff only where they influence that core journey.", "Screenshots, anonymized documents, current spreadsheets, and a live walkthrough often explain more than a long feature list. Remove personal or confidential information before sharing."], diagram: ["Trigger", "User action", "Business decision", "Recorded outcome"] },
      { id: "systems", title: "List existing systems, integrations, and data", body: ["State whether there is an existing website, application, backend, API, database, identity provider, or vendor contract. Provide available documentation and access constraints. Do not assume an existing backend is reusable until its API, permissions, and workflow coverage are reviewed.", "List accounting, payment, mapping, messaging, analytics, or industry services that must connect. For data migration, describe sources, formats, approximate volume, quality concerns, and whether historical records must remain available."], bullets: ["Existing web, mobile, backend, and admin software", "API documentation and technical ownership", "Third-party integrations and contracts", "Data sources, volume, quality, and retention", "Security, compliance, hosting, or residency constraints"] },
      { id: "priority", title: "Separate must-haves from launch ambitions", body: ["Identify the smallest outcome that makes the first release useful and which platforms are required at launch. Explain deadlines and why they exist; a regulatory date differs from a preferred marketing window.", "Mark ideas that can be manual, deferred, or tested later. This gives the estimator room to propose phases instead of pricing every possibility as one large commitment."], table: { caption: "A concise project brief", headers: ["Area", "What to provide"], rows: [["Problem", "Current process and desired outcome"], ["Users", "Primary and supporting roles"], ["Workflow", "Start-to-finish core journey"], ["Scope", "Must-have first release and later ideas"], ["Technology context", "Existing systems, API, integrations, data"], ["Constraints", "Timing, security, budget context, ownership"]] } },
      { id: "not-needed", title: "What you do not need before making contact", body: ["You do not need every screen designed, a final database schema, a chosen framework, or a perfect requirements document. Prescribing technology too early can hide simpler options and transfer architecture decisions away from the people who will be responsible for delivery.", "You also do not need false certainty. Clearly identified unknowns are useful. They can become discovery questions, prototypes, or technical spikes rather than expensive surprises."],
      },
      { id: "estimate", title: "What a useful estimate should give back", body: ["Expect a summary of understood scope, assumptions, exclusions, dependencies, likely phases, risks, and a pricing or effort model appropriate to the certainty available. Ask what would change the estimate and how scope decisions are recorded.", "The first conversation should improve the project definition even if no build follows. A clear brief and transparent response make it easier to compare approaches on substance rather than headline numbers."],
      },
    ],
    primaryLink: { href: "/solutions/custom-software-cost", label: "Discuss your project scope", description: "Use your brief to begin a grounded estimate and scoping conversation." },
    relatedLinks: [{ href: "/contact?intent=project-scope", label: "Discuss your project scope" }, { href: "/services/mvp-development", label: "MVP development" }, { href: "/services/custom-business-software", label: "Custom business software" }],
  },
];
