import {
  EXPENSE_PLAY_URL,
  FLASHCARDS_PLAY_URL,
  HABIT_PLAY_URL,
  ISKRAUG_PLAY_URL,
  MEDITATION_PLAY_URL,
  PUBPLAY_SITE_URL,
  TRADESMATE_SITE_URL,
  TODO_PLAY_URL,
  UNISCAN_PLAY_URL,
} from "@/lib/constants";

export type WorkProduct = {
  slug: string;
  title: string;
  summary: string;
  classification: string;
  platform: string;
  strongestCapability: string;
  tags: string[];
  thumb: string;
  serviceHref: string;
  serviceLabel: string;
  externalHref?: string;
  externalLabel?: string;
  priority: "platform" | "application";
};

export const workProducts: WorkProduct[] = [
  {
    slug: "tradesmate",
    title: "TradesMate: Jobs, Quotes & Invoices",
    summary: "A connected trade-business workflow for customers, jobs, schedules, quotes, invoices, payments, costs, and financial visibility.",
    classification: "Commercial product · Business software",
    platform: "Android + API",
    strongestCapability: "Interconnected field-service operations",
    tags: ["React Native", "FastAPI", "PostgreSQL"],
    thumb: "/demos/preview/tradesmate.png",
    serviceHref: "/services/custom-business-software",
    serviceLabel: "Custom Business Software",
    externalHref: TRADESMATE_SITE_URL,
    externalLabel: "Visit TradesMate",
    priority: "platform",
  },
  {
    slug: "come-together",
    title: "Come Together: Local Clubs Platform",
    summary: "A public web and Android platform for club discovery, event booking, capacity, waitlists, attendance, and repeat participation.",
    classification: "Pilot platform · SaaS",
    platform: "Web + Android + API",
    strongestCapability: "Multi-user event and membership workflows",
    tags: ["Next.js", "React Native", "FastAPI"],
    thumb: "/demos/preview/come-together.png",
    serviceHref: "/services/saas-development",
    serviceLabel: "SaaS Development",
    externalHref: "https://hellolocalclubs.com",
    externalLabel: "Visit live platform",
    priority: "platform",
  },
  {
    slug: "pubplay",
    title: "PubPlay: Pub Games Night System",
    summary: "A venue platform joining an Android host tablet, QR player web app, live fixtures, scoring, TV display, and event archive.",
    classification: "Commercial product · Venue platform",
    platform: "Android + Web + TV + API",
    strongestCapability: "Synchronized multi-screen live events",
    tags: ["React Native", "Web", "FastAPI"],
    thumb: "/demos/preview/pubplay.jpg",
    serviceHref: "/services/saas-development",
    serviceLabel: "SaaS Development",
    externalHref: PUBPLAY_SITE_URL,
    externalLabel: "Visit PubPlay",
    priority: "platform",
  },
  {
    slug: "studyflow",
    title: "StudyFlow Flashcards",
    summary: "A local-first flashcard product with spaced review, due-card scheduling, recall ratings, statistics, reminders, and Lifetime Pro.",
    classification: "Commercial Android application",
    platform: "Android",
    strongestCapability: "Structured local-first learning state",
    tags: ["React Native", "Local-first", "Billing"],
    thumb: "/demos/preview/studyflow.png",
    serviceHref: "/services/mobile-app-development",
    serviceLabel: "Mobile App Development",
    externalHref: FLASHCARDS_PLAY_URL,
    externalLabel: "Google Play",
    priority: "application",
  },
  {
    slug: "uniscan",
    title: "Docs Scan OCR Encrypt & Share",
    summary: "A privacy-first scanner with on-device OCR, native processing, encrypted exports, vault storage, and secure file workflows.",
    classification: "Commercial Android application",
    platform: "Android",
    strongestCapability: "Native OCR and protected documents",
    tags: ["React Native", "OCR", "Encryption"],
    thumb: "/demos/preview/uniscan.jpg",
    serviceHref: "/services/react-native-development",
    serviceLabel: "React Native Development",
    externalHref: UNISCAN_PLAY_URL,
    externalLabel: "Google Play",
    priority: "application",
  },
  {
    slug: "iskra",
    title: "Iskra Trading Mobile Catalog & Orders",
    summary: "A mobile product catalogue and ordering workflow with offline cart behavior, validated totals, order history, and backend exports.",
    classification: "Business mobile application",
    platform: "Android + API",
    strongestCapability: "Field sales and ordering integration",
    tags: ["React Native", "FastAPI", "SQLite/PostgreSQL"],
    thumb: "/demos/preview/iskra.jpg",
    serviceHref: "/services/backend-api-development",
    serviceLabel: "Backend & API Development",
    externalHref: ISKRAUG_PLAY_URL,
    externalLabel: "Google Play",
    priority: "application",
  },
  {
    slug: "expense",
    title: "ExpenseFlow Smart Tracker",
    summary: "A focused personal expense tracker for quick entries, categories, monthly budgets, recent spending, and local-first records.",
    classification: "Commercial Android application",
    platform: "Android",
    strongestCapability: "Structured financial records and reporting",
    tags: ["React Native", "Finance", "Local-first"],
    thumb: "/demos/preview/expense.png",
    serviceHref: "/services/mobile-app-development",
    serviceLabel: "Mobile App Development",
    externalHref: EXPENSE_PLAY_URL,
    externalLabel: "Google Play",
    priority: "application",
  },
  {
    slug: "habit",
    title: "HabitFlow Daily Habit Tracker",
    summary: "A calm habit tracker with daily check-ins, streaks, heatmaps, reminders, and consistency statistics.",
    classification: "Commercial Android application",
    platform: "Android",
    strongestCapability: "Repeated-state tracking and visualization",
    tags: ["React Native", "Habits", "Local-first"],
    thumb: "/demos/preview/habit.png",
    serviceHref: "/services/mobile-app-development",
    serviceLabel: "Mobile App Development",
    externalHref: HABIT_PLAY_URL,
    externalLabel: "Google Play",
    priority: "application",
  },
  {
    slug: "meditation",
    title: "MeditationFlow: Calm Timer",
    summary: "A quiet meditation timer with breathing practices, reminders, session history, statistics, and private reflection notes.",
    classification: "Commercial Android application",
    platform: "Android",
    strongestCapability: "Timer, reminders, and private session state",
    tags: ["React Native", "Wellbeing", "Local-first"],
    thumb: "/demos/preview/meditation.png",
    serviceHref: "/services/mobile-app-development",
    serviceLabel: "Mobile App Development",
    externalHref: MEDITATION_PLAY_URL,
    externalLabel: "Google Play",
    priority: "application",
  },
  {
    slug: "todo",
    title: "Momentum TODO Focus & Routine",
    summary: "A lightweight productivity app combining tasks, routines, streaks, statistics, offline storage, and multilingual planning.",
    classification: "Commercial Android application",
    platform: "Android",
    strongestCapability: "Tasks and repeated routines in one model",
    tags: ["React Native", "Productivity", "Offline"],
    thumb: "/demos/preview/todo.png",
    serviceHref: "/services/react-native-development",
    serviceLabel: "React Native Development",
    externalHref: TODO_PLAY_URL,
    externalLabel: "Google Play",
    priority: "application",
  },
];

export function getWorkProduct(slug: string) {
  return workProducts.find((product) => product.slug === slug);
}
